-- v1.2.0-alpha.4: company-level organization governance.
-- These additions keep legacy records readable while making new department
-- ownership, collaboration, department roles and historical corrections explicit.

ALTER TABLE divisions ADD COLUMN IF NOT EXISTS code TEXT NOT NULL DEFAULT '';
ALTER TABLE divisions ADD COLUMN IF NOT EXISTS manager_user_id BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_divisions_code_present
    ON divisions(code) WHERE code <> '' AND deleted_at IS NULL;

-- A project has one owner department and can explicitly expose itself to
-- selected collaborating departments. The owner is always implicit and is
-- therefore not duplicated in this relation.
CREATE TABLE IF NOT EXISTS project_collaboration_divisions (
    project_id BIGINT NOT NULL,
    division_id BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (project_id, division_id)
);
CREATE INDEX IF NOT EXISTS idx_project_collaboration_division
    ON project_collaboration_divisions(division_id, project_id);

-- Department role = an existing role template-derived role applied to one
-- department and business domain. Existing user_roles remain compatible;
-- new assignments add a restrictive department scope instead of granting a
-- hidden global range.
CREATE TABLE IF NOT EXISTS department_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    division_id BIGINT NOT NULL,
    business_domain TEXT NOT NULL DEFAULT 'all',
    is_department_admin BIGINT NOT NULL DEFAULT 0,
    is_active BIGINT NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE(role_id, division_id, business_domain)
);
CREATE INDEX IF NOT EXISTS idx_department_roles_division
    ON department_roles(division_id, is_active);

CREATE TABLE IF NOT EXISTS user_department_roles (
    user_id BIGINT NOT NULL,
    department_role_id BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (user_id, department_role_id)
);
CREATE INDEX IF NOT EXISTS idx_user_department_roles_user
    ON user_department_roles(user_id, department_role_id);

-- Sample-information records did not yet carry immutable business ownership.
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS project_division_id BIGINT;
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS project_division_name_snapshot TEXT NOT NULL DEFAULT '';
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS execution_division_id BIGINT;
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS execution_division_name_snapshot TEXT NOT NULL DEFAULT '';
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS execution_group_id BIGINT;
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS execution_group_name_snapshot TEXT NOT NULL DEFAULT '';
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS submitted_division_id BIGINT;
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS submitted_division_name_snapshot TEXT NOT NULL DEFAULT '';
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS business_user_id BIGINT;
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS business_username_snapshot TEXT NOT NULL DEFAULT '';
ALTER TABLE sample_info_records ADD COLUMN IF NOT EXISTS ownership_status TEXT NOT NULL DEFAULT 'confirmed';

-- Add the missing submitter dimension to RD records and ownership status to
-- every business record. A blank historical snapshot is intentionally marked
-- pending rather than guessed by the system.
ALTER TABLE rd_work_records ADD COLUMN IF NOT EXISTS submitted_division_id BIGINT;
ALTER TABLE rd_work_records ADD COLUMN IF NOT EXISTS submitted_division_name_snapshot TEXT NOT NULL DEFAULT '';
ALTER TABLE rd_work_records ADD COLUMN IF NOT EXISTS ownership_status TEXT NOT NULL DEFAULT 'confirmed';
ALTER TABLE work_records ADD COLUMN IF NOT EXISTS ownership_status TEXT NOT NULL DEFAULT 'confirmed';

CREATE TABLE IF NOT EXISTS record_ownership_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_type TEXT NOT NULL,
    record_id BIGINT NOT NULL,
    project_division_id BIGINT,
    execution_division_id BIGINT,
    execution_group_id BIGINT,
    submitted_division_id BIGINT,
    confirmed_by_user_id BIGINT,
    confirmed_by_username TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    confirmed_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE(record_type, record_id)
);
CREATE INDEX IF NOT EXISTS idx_record_ownership_confirmations_type
    ON record_ownership_confirmations(record_type, confirmed_at DESC);

-- Structured audit fields distinguish the account that clicked the button
-- from the actual business person selected through a public account.
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS operator_user_id BIGINT;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS operator_username_snapshot TEXT NOT NULL DEFAULT '';
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS business_user_id BIGINT;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS business_username_snapshot TEXT NOT NULL DEFAULT '';
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS business_division_id BIGINT;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS business_division_name_snapshot TEXT NOT NULL DEFAULT '';

UPDATE divisions SET code = 'D' || id WHERE code = '';

UPDATE sample_info_records s
SET execution_group_id = s.group_id,
    execution_group_name_snapshot = COALESCE(NULLIF(s.lab_name, ''), ''),
    execution_division_id = COALESCE(
        s.division_id,
        (SELECT g.division_id FROM project_groups g WHERE g.id = s.group_id)
    ),
    execution_division_name_snapshot = COALESCE(
        (SELECT d.name
         FROM divisions d
         WHERE d.id = COALESCE(
             s.division_id,
             (SELECT g.division_id FROM project_groups g WHERE g.id = s.group_id)
         )),
        ''
    ),
    submitted_division_id = COALESCE(
        s.division_id,
        (SELECT g.division_id FROM project_groups g WHERE g.id = s.group_id)
    ),
    submitted_division_name_snapshot = COALESCE(
        (SELECT d.name
         FROM divisions d
         WHERE d.id = COALESCE(
             s.division_id,
             (SELECT g.division_id FROM project_groups g WHERE g.id = s.group_id)
         )),
        ''
    ),
    business_user_id = s.created_by_user_id,
    business_username_snapshot = COALESCE(NULLIF(s.user_name, ''), s.created_by_username_snapshot, ''),
    ownership_status = CASE
        WHEN COALESCE(
            s.division_id,
            (SELECT g.division_id FROM project_groups g WHERE g.id = s.group_id)
        ) IS NULL THEN 'pending_confirmation'
        ELSE 'confirmed'
    END
WHERE s.group_id IS NOT NULL
  AND (s.execution_division_id IS NULL OR s.execution_group_id IS NULL);

UPDATE sample_info_records s
SET ownership_status = 'pending_confirmation'
WHERE s.execution_division_id IS NULL;

UPDATE rd_work_records r
SET submitted_division_id = COALESCE(r.submitted_division_id, r.project_division_id),
    submitted_division_name_snapshot = COALESCE(
        NULLIF(r.submitted_division_name_snapshot, ''),
        r.project_division_name_snapshot,
        ''
    ),
    ownership_status = CASE
        WHEN r.execution_division_id IS NULL THEN 'pending_confirmation'
        ELSE r.ownership_status
    END;

UPDATE work_records SET ownership_status = 'pending_confirmation'
WHERE execution_division_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_sample_info_execution_division
    ON sample_info_records(execution_division_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_sample_info_project_division
    ON sample_info_records(project_division_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_sample_info_ownership_status
    ON sample_info_records(ownership_status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_work_records_ownership_status
    ON work_records(ownership_status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_rd_work_records_ownership_status
    ON rd_work_records(ownership_status) WHERE deleted_at IS NULL;

INSERT INTO schema_migrations(version)
VALUES ('1.2.0-alpha.4-organization-governance')
ON CONFLICT DO NOTHING;
