-- v1.2.0-alpha.1: company-level role templates and role provenance.
CREATE TABLE IF NOT EXISTS role_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  is_system BIGINT NOT NULL DEFAULT 1,
  sort_order BIGINT NOT NULL DEFAULT 0,
  deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS role_template_permissions (
  template_id BIGINT NOT NULL,
  permission_key TEXT NOT NULL,
  PRIMARY KEY (template_id, permission_key)
);

ALTER TABLE roles ADD COLUMN IF NOT EXISTS template_id BIGINT;

CREATE UNIQUE INDEX IF NOT EXISTS uq_role_templates_name
  ON role_templates(name);

CREATE INDEX IF NOT EXISTS idx_roles_template_id
  ON roles(template_id);

INSERT INTO role_templates(name, description, is_system, sort_order)
VALUES
  ('研发送样员模板', '创建送样、编辑本人送样、确认本人退回', 1, 10),
  ('分析检测员模板', '待取样、取样、工作量录入、撤回本人取样', 1, 20),
  ('分析检测组长模板', '分析检测员权限、退回、审核和部门内查看', 1, 30),
  ('样品登记员模板', '样品信息登记和本人记录处理', 1, 40),
  ('样品登记组长模板', '样品登记退回、确认退回和部门内处理', 1, 50),
  ('部门统计查看员模板', '查看本部门统计和导出', 1, 60),
  ('部门管理员模板', '管理本部门用户和部门角色', 1, 70),
  ('系统管理员模板', '全公司配置、审计和全公司数据', 1, 80)
ON CONFLICT (name) DO NOTHING;

INSERT INTO role_template_permissions(template_id, permission_key)
SELECT t.id, p.permission_key
FROM role_templates t
JOIN (VALUES
  ('研发送样员模板','entry:sample'),
  ('研发送样员模板','entry:sample-info'),
  ('研发送样员模板','sample-info:create'),
  ('研发送样员模板','sample-info:edit-own'),
  ('研发送样员模板','records:rd:edit-created'),
  ('研发送样员模板','records:rd:edit-subject'),
  ('研发送样员模板','records:rd:return-confirm'),
  ('分析检测员模板','entry:workload'),
  ('分析检测员模板','entry:sample-info'),
  ('分析检测员模板','sample:collect'),
  ('分析检测员模板','sample:withdraw'),
  ('分析检测员模板','sample:complete'),
  ('分析检测员模板','records:work:select-detector'),
  ('分析检测组长模板','entry:workload'),
  ('分析检测组长模板','entry:sample-info'),
  ('分析检测组长模板','sample:collect'),
  ('分析检测组长模板','sample:withdraw'),
  ('分析检测组长模板','sample:complete'),
  ('分析检测组长模板','sample:return'),
  ('分析检测组长模板','records:work:select-detector'),
  ('分析检测组长模板','stats:portal:workload'),
  ('分析检测组长模板','records:work:view-scope'),
  ('样品登记员模板','entry:sample-info'),
  ('样品登记员模板','sample-info:create'),
  ('样品登记员模板','sample-info:edit-own'),
  ('样品登记员模板','sample-info:collect'),
  ('样品登记员模板','sample-info:complete'),
  ('样品登记员模板','sample-info:return-confirm'),
  ('样品登记组长模板','entry:sample-info'),
  ('样品登记组长模板','sample-info:create'),
  ('样品登记组长模板','sample-info:edit-own'),
  ('样品登记组长模板','sample-info:collect'),
  ('样品登记组长模板','sample-info:complete'),
  ('样品登记组长模板','sample-info:return'),
  ('样品登记组长模板','sample-info:return-confirm'),
  ('样品登记组长模板','manage:sampleinfo'),
  ('部门统计查看员模板','stats:portal:workload'),
  ('部门统计查看员模板','records:work:view-scope'),
  ('部门统计查看员模板','stats:workload:access'),
  ('部门统计查看员模板','manage:data-governance:export'),
  ('部门管理员模板','manage:users'),
  ('部门管理员模板','manage:roles'),
  ('部门管理员模板','manage:divisions'),
  ('系统管理员模板','*')
) AS p(template_name, permission_key) ON p.template_name=t.name
WHERE NOT EXISTS (
  SELECT 1 FROM role_template_permissions x
  WHERE x.template_id=t.id AND x.permission_key=p.permission_key
);

INSERT INTO schema_migrations(version)
VALUES ('1.2.0-alpha.1-role-templates')
ON CONFLICT DO NOTHING;
