import json
import sys
from pathlib import Path


def ident(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def pg_type(source_type: str) -> str:
    value = source_type.upper()
    if "INT" in value:
        return "BIGINT"
    if "REAL" in value or "FLOA" in value or "DOUB" in value:
        return "DOUBLE PRECISION"
    if "BLOB" in value:
        return "BYTEA"
    return "TEXT"


def pg_default(value):
    if value is None or str(value).upper() == "NULL":
        return None
    text = str(value)
    if text in {"datetime('now')", "datetime('now','localtime')"}:
        return "to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')"
    return text


def main() -> None:
    source = Path(sys.argv[1])
    target = Path(sys.argv[2])
    schema = json.loads(source.read_text(encoding="utf-8"))
    statements = [
        "BEGIN;",
        "CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);",
    ]
    foreign_keys = []
    indexes = []
    for table in schema["tables"]:
        pk_columns = sorted(
            [c for c in table["columns"] if c["primary_key_order"]],
            key=lambda c: c["primary_key_order"],
        )
        single_integer_pk = len(pk_columns) == 1 and "INT" in pk_columns[0]["type"].upper()
        definitions = []
        for column in table["columns"]:
            definition = f"{ident(column['name'])} {pg_type(column['type'])}"
            if single_integer_pk and column["name"] == pk_columns[0]["name"]:
                definition += " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            else:
                if column["not_null"]:
                    definition += " NOT NULL"
                default = pg_default(column["default"])
                if default is not None:
                    definition += f" DEFAULT {default}"
            definitions.append(definition)
        if pk_columns and not single_integer_pk:
            definitions.append("PRIMARY KEY (" + ", ".join(ident(c["name"]) for c in pk_columns) + ")")
        statements.append(f"CREATE TABLE IF NOT EXISTS {ident(table['name'])} (\n  " + ",\n  ".join(definitions) + "\n);")
        for fk in table["foreign_keys"]:
            name = f"fk_{table['name']}_{fk['from']}_{fk['id']}"
            clause = (
                f"ALTER TABLE {ident(table['name'])} ADD CONSTRAINT {ident(name)} "
                f"FOREIGN KEY ({ident(fk['from'])}) REFERENCES {ident(fk['table'])} ({ident(fk['to'])})"
            )
            if fk["on_update"] and fk["on_update"] != "NO ACTION":
                clause += " ON UPDATE " + fk["on_update"]
            if fk["on_delete"] and fk["on_delete"] != "NO ACTION":
                clause += " ON DELETE " + fk["on_delete"]
            foreign_keys.append(clause + ";")
        for index in table["indexes"]:
            if index["origin"] == "pk" or not index["columns"]:
                continue
            unique = "UNIQUE " if index["unique"] else ""
            indexes.append(
                f"CREATE {unique}INDEX IF NOT EXISTS {ident(index['name'])} ON {ident(table['name'])} "
                f"({', '.join(ident(c) for c in index['columns'])});"
            )
    statements.extend(foreign_keys)
    statements.extend(indexes)
    statements.append("INSERT INTO schema_migrations(version) VALUES ('1.1.0-beta.1') ON CONFLICT DO NOTHING;")
    statements.append("COMMIT;")
    target.write_text("\n\n".join(statements) + "\n", encoding="utf-8")
    print(f"generated PostgreSQL schema with {len(schema['tables'])} tables")


if __name__ == "__main__":
    main()
