-- v2.2.0: source-format help tutorial attachments.
CREATE TABLE IF NOT EXISTS help_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  filename TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_type TEXT NOT NULL DEFAULT 'bin',
  file_size BIGINT NOT NULL DEFAULT 0,
  is_visible BIGINT NOT NULL DEFAULT 1,
  sort_order BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  deleted_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_help_attachments_visible ON help_attachments(is_visible, sort_order, id);
INSERT INTO schema_migrations(version) VALUES ('2.2.0-help-tutorial') ON CONFLICT DO NOTHING;
