CREATE TABLE IF NOT EXISTS notification_channels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  channel_type TEXT NOT NULL DEFAULT 'dingtalk_robot',
  webhook_url TEXT NOT NULL,
  secret TEXT NOT NULL DEFAULT '',
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS notification_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  event_type TEXT NOT NULL DEFAULT 'sample_submitted',
  group_id BIGINT,
  project_name TEXT NOT NULL DEFAULT '',
  detection_type TEXT NOT NULL DEFAULT '',
  sample_info_type_key TEXT NOT NULL DEFAULT '',
  channel_id BIGINT,
  recipient_user_ids TEXT NOT NULL DEFAULT '[]',
  is_default BIGINT NOT NULL DEFAULT 0,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id BIGINT NOT NULL,
  dedupe_key TEXT NOT NULL UNIQUE,
  payload_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  next_attempt_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS notification_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  channel_id BIGINT NOT NULL,
  status TEXT NOT NULL,
  attempts BIGINT NOT NULL DEFAULT 0,
  response_summary TEXT NOT NULL DEFAULT '',
  last_error TEXT NOT NULL DEFAULT '',
  next_attempt_at TEXT,
  sent_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(event_id, channel_id)
);

CREATE TABLE IF NOT EXISTS in_app_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  target_url TEXT NOT NULL DEFAULT '',
  is_read BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(event_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_notification_events_pending ON notification_events(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_notification_rules_match ON notification_rules(event_type, is_active, group_id);
CREATE INDEX IF NOT EXISTS idx_in_app_notifications_user ON in_app_notifications(user_id, is_read, created_at);

INSERT INTO schema_migrations(version) VALUES ('1.1.0-beta.10-notifications') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,permission_key)
SELECT r.id,'manage:notifications' FROM roles r
WHERE r.name IN ('系统管理员','分析检测组长')
  AND NOT EXISTS(SELECT 1 FROM role_permissions rp WHERE rp.role_id=r.id AND rp.permission_key='manage:notifications');
