-- v1.1.5-beta.1: type-specific sample field rules, server-side drafts and notification templates.
ALTER TABLE sample_info_column_visibility
  ADD COLUMN IF NOT EXISTS is_required BIGINT NOT NULL DEFAULT 0;

UPDATE sample_info_column_visibility v
SET is_required = c.is_required
FROM sample_info_columns c
WHERE c.id = v.column_id;

INSERT INTO sample_info_column_visibility(type_key, column_id, is_visible, is_required)
SELECT t.type_key, c.id, 1, c.is_required
FROM sample_info_types t
CROSS JOIN sample_info_columns c
WHERE t.is_active = 1 AND c.deleted_at IS NULL
ON CONFLICT(type_key, column_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS sample_info_drafts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  username_snapshot TEXT NOT NULL,
  type_key TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  payload_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  submitted_at TEXT,
  deleted_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_sample_info_drafts_owner ON sample_info_drafts(user_id, status, updated_at);

CREATE TABLE IF NOT EXISTS sample_info_draft_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  draft_id BIGINT NOT NULL REFERENCES sample_info_drafts(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  stored_name TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  file_type TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  deleted_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_sample_info_draft_attachments_draft ON sample_info_draft_attachments(draft_id);

CREATE TABLE IF NOT EXISTS notification_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  field_config_json TEXT NOT NULL,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);
INSERT INTO notification_templates(event_key,title,field_config_json,is_active)
VALUES (
  'sample_submitted',
  '新送样待取样',
  '[{"key":"batch_no","label":"批号","enabled":true,"bold":true},{"key":"business_no","label":"送样编号","enabled":true,"bold":false},{"key":"submitted_at","label":"送样时间","enabled":true,"bold":false},{"key":"submitted_by","label":"送样人","enabled":true,"bold":false},{"key":"division_name","label":"部门","enabled":true,"bold":false},{"key":"lab_name","label":"实验室","enabled":true,"bold":false},{"key":"project_name","label":"项目","enabled":true,"bold":false},{"key":"detection_type","label":"检测类型","enabled":true,"bold":false},{"key":"method_name","label":"方法","enabled":true,"bold":false},{"key":"instrument_code","label":"仪器","enabled":true,"bold":false},{"key":"quantity","label":"数量","enabled":true,"bold":true},{"key":"attachment_count","label":"附件","enabled":true,"bold":false}]',
  1
) ON CONFLICT(event_key) DO NOTHING;

INSERT INTO schema_migrations(version) VALUES ('1.1.5-beta.1-sample-rules-drafts') ON CONFLICT DO NOTHING;
