CREATE TABLE IF NOT EXISTS method_type_visibility (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  method_type_id BIGINT NOT NULL REFERENCES method_types(id),
  group_id BIGINT NOT NULL REFERENCES project_groups(id),
  portal TEXT NOT NULL,
  is_visible BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  CONSTRAINT uq_method_type_visibility UNIQUE (method_type_id, group_id, portal),
  CONSTRAINT ck_method_type_visibility_portal CHECK (portal IN ('work','rd','sample_info'))
);
CREATE INDEX IF NOT EXISTS idx_method_type_visibility_group_portal
  ON method_type_visibility(group_id, portal, method_type_id);
INSERT INTO schema_migrations(version)
VALUES ('2.2.16-detection-type-visibility') ON CONFLICT DO NOTHING;
