BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS "audit_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "action" TEXT NOT NULL,
  "table_name" TEXT NOT NULL,
  "record_id" BIGINT,
  "user_name" TEXT DEFAULT '',
  "detail" TEXT DEFAULT '',
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "module" TEXT NOT NULL DEFAULT 'shared',
  "business_no" TEXT NOT NULL DEFAULT '',
  "before_json" TEXT,
  "after_json" TEXT,
  "source" TEXT NOT NULL DEFAULT 'application',
  "user_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "backup_file_trash" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "original_name" TEXT NOT NULL,
  "stored_name" TEXT NOT NULL,
  "file_size" BIGINT NOT NULL DEFAULT 0,
  "deleted_at" TEXT,
  "restored_at" TEXT,
  "purged_at" TEXT
);

CREATE TABLE IF NOT EXISTS "divisions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "sort_order" BIGINT NOT NULL DEFAULT 0,
  "color" TEXT NOT NULL DEFAULT '#1976d2',
  "is_active" BIGINT NOT NULL DEFAULT 1,
  "show_in_work" BIGINT NOT NULL DEFAULT 1,
  "show_in_rd" BIGINT NOT NULL DEFAULT 1,
  "show_in_sample_info" BIGINT NOT NULL DEFAULT 1,
  "deleted_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS "governance_confirmations" (
  "token" TEXT,
  "module" TEXT NOT NULL,
  "start_at" TEXT NOT NULL,
  "end_at" TEXT NOT NULL,
  "request_user_id" BIGINT NOT NULL,
  "expires_at" TEXT NOT NULL,
  "used_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY ("token")
);

CREATE TABLE IF NOT EXISTS "governance_import_batches" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "module" TEXT NOT NULL,
  "file_name" TEXT NOT NULL,
  "file_sha256" TEXT NOT NULL,
  "operator_user_id" BIGINT NOT NULL,
  "operator_username" TEXT NOT NULL,
  "total_rows" BIGINT NOT NULL DEFAULT 0,
  "inserted_rows" BIGINT NOT NULL DEFAULT 0,
  "skipped_rows" BIGINT NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS "governance_jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "module" TEXT NOT NULL,
  "job_type" TEXT NOT NULL,
  "start_at" TEXT DEFAULT '',
  "end_at" TEXT DEFAULT '',
  "operator_user_id" BIGINT NOT NULL,
  "operator_username" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "detail" TEXT NOT NULL DEFAULT '',
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS "help_articles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" TEXT NOT NULL,
  "content_html" TEXT NOT NULL DEFAULT '',
  "toc_json" TEXT,
  "source_file" TEXT,
  "is_visible" BIGINT DEFAULT 1,
  "sort_order" BIGINT DEFAULT 0,
  "created_at" TEXT DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" TEXT DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "help_documents" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" TEXT NOT NULL,
  "filename" TEXT NOT NULL,
  "file_path" TEXT NOT NULL,
  "file_type" TEXT NOT NULL,
  "file_size" BIGINT DEFAULT 0,
  "is_visible" BIGINT DEFAULT 1,
  "sort_order" BIGINT DEFAULT 0,
  "created_at" TEXT DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" TEXT DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "page_count" BIGINT DEFAULT 0,
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "high_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "sort_order" BIGINT DEFAULT 0,
  "is_active" BIGINT NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS "import_mappings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "header_pattern" TEXT NOT NULL,
  "match_mode" TEXT NOT NULL DEFAULT 'contains',
  "target_table" TEXT NOT NULL,
  "default_type" TEXT DEFAULT '',
  "priority" BIGINT NOT NULL DEFAULT 100,
  "is_active" BIGINT NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS "instruments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL DEFAULT '',
  "instrument_type" TEXT NOT NULL,
  "is_active" BIGINT NOT NULL DEFAULT 1,
  "notes" TEXT NOT NULL DEFAULT '',
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "log_archive_batches" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "archive_type" TEXT NOT NULL,
  "start_at" TEXT,
  "end_at" TEXT,
  "file_path" TEXT NOT NULL,
  "sha256" TEXT NOT NULL,
  "record_count" BIGINT NOT NULL DEFAULT 0,
  "file_size" BIGINT NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'completed',
  "created_by" TEXT NOT NULL DEFAULT 'system',
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "verified_at" TEXT,
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "maintenance_jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_type" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "detail" TEXT NOT NULL DEFAULT '',
  "started_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "completed_at" TEXT,
  "created_by" TEXT NOT NULL DEFAULT 'system'
);

CREATE TABLE IF NOT EXISTS "method_type_links" (
  "method_id" BIGINT NOT NULL,
  "method_type_id" BIGINT NOT NULL,
  PRIMARY KEY ("method_id", "method_type_id"),
  CONSTRAINT "uq_method_type_links_method_id" UNIQUE ("method_id")
);

CREATE TABLE IF NOT EXISTS "method_types" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "sort_order" BIGINT DEFAULT 0,
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "methods" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "full_name" TEXT DEFAULT '',
  "coefficient" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  "notes" TEXT DEFAULT '',
  "is_active" BIGINT NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "amount" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  "multiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  "method_code" TEXT NOT NULL DEFAULT '',
  "instrument_id" BIGINT,
  "show_in_work" BIGINT NOT NULL DEFAULT 1,
  "show_in_rd" BIGINT NOT NULL DEFAULT 1,
  "show_in_sample_info" BIGINT NOT NULL DEFAULT 1,
  "is_common" BIGINT NOT NULL DEFAULT 0,
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "personnel_change_feedback_projects" (
  "feedback_id" BIGINT NOT NULL,
  "project_id" BIGINT NOT NULL,
  PRIMARY KEY ("feedback_id", "project_id")
);

CREATE TABLE IF NOT EXISTS "personnel_change_feedbacks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notice_no" TEXT NOT NULL,
  "lab_id" BIGINT NOT NULL,
  "responsible_user_id" BIGINT,
  "responsible_name_snapshot" TEXT NOT NULL DEFAULT '',
  "change_type" TEXT NOT NULL,
  "person_name" TEXT NOT NULL,
  "effective_at" TEXT NOT NULL,
  "notes" TEXT NOT NULL DEFAULT '',
  "status" TEXT NOT NULL DEFAULT '有效',
  "created_by_user_id" BIGINT NOT NULL,
  "created_by_username" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "project_groups" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "sort_order" BIGINT NOT NULL DEFAULT 0,
  "show_in_work" BIGINT NOT NULL DEFAULT 1,
  "show_in_rd" BIGINT NOT NULL DEFAULT 1,
  "show_in_sample_info" BIGINT NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "division_id" BIGINT,
  "deleted_at" TEXT
);

-- Detection type visibility is an override layer: no row means visible.
CREATE TABLE IF NOT EXISTS "method_type_visibility" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "method_type_id" BIGINT NOT NULL REFERENCES method_types(id),
  "group_id" BIGINT NOT NULL REFERENCES project_groups(id),
  "portal" TEXT NOT NULL,
  "is_visible" BIGINT NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  CONSTRAINT "uq_method_type_visibility" UNIQUE (method_type_id, group_id, portal),
  CONSTRAINT "ck_method_type_visibility_portal" CHECK (portal IN ('work','rd','sample_info'))
);
CREATE INDEX IF NOT EXISTS "idx_method_type_visibility_group_portal"
  ON method_type_visibility(group_id, portal, method_type_id);

CREATE TABLE IF NOT EXISTS "project_lab_links" (
  "project_id" BIGINT NOT NULL,
  "group_id" BIGINT NOT NULL,
  PRIMARY KEY ("project_id", "group_id")
);

CREATE TABLE IF NOT EXISTS "project_method_links" (
  "project_id" BIGINT NOT NULL,
  "method_id" BIGINT NOT NULL,
  PRIMARY KEY ("project_id", "method_id")
);

CREATE TABLE IF NOT EXISTS "projects" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" BIGINT NOT NULL,
  "name" TEXT NOT NULL,
  "full_name" TEXT DEFAULT '',
  "notes" TEXT DEFAULT '',
  "sort_order" BIGINT NOT NULL DEFAULT 0,
  "is_active" BIGINT NOT NULL DEFAULT 1,
  "show_in_work" BIGINT NOT NULL DEFAULT 1,
  "show_in_rd" BIGINT NOT NULL DEFAULT 1,
  "show_in_sample_info" BIGINT NOT NULL DEFAULT 1,
  "project_status" TEXT NOT NULL DEFAULT 'ongoing',
  "archived_at" TEXT,
  "archived_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "coefficient" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  "method_type" TEXT NOT NULL DEFAULT '其他',
  "associated_lab_ids" TEXT NOT NULL DEFAULT '',
  "associated_method_ids" TEXT NOT NULL DEFAULT '',
  "high_item_id" BIGINT,
  "high_item" TEXT,
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "rd_record_columns" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "data_type" TEXT NOT NULL DEFAULT 'text',
  "width" BIGINT DEFAULT 100,
  "sort_order" BIGINT DEFAULT 0,
  "is_predefined" BIGINT NOT NULL DEFAULT 1,
  "is_required" BIGINT NOT NULL DEFAULT 0,
  "is_active" BIGINT NOT NULL DEFAULT 1,
  "show_in_list" BIGINT NOT NULL DEFAULT 1,
  "show_in_form" BIGINT NOT NULL DEFAULT 1,
  "show_in_export" BIGINT NOT NULL DEFAULT 1,
  "options" TEXT NOT NULL DEFAULT '',
  "option_detail_rules" TEXT NOT NULL DEFAULT '',
  "default_value" TEXT NOT NULL DEFAULT '',
  "placeholder" TEXT NOT NULL DEFAULT '',
  "applicable_types" TEXT NOT NULL DEFAULT '',
  "entry_row" BIGINT NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" TEXT DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS "rd_work_records" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" BIGINT NOT NULL,
  "method_id" BIGINT,
  "user_name" TEXT NOT NULL,
  "quantity" BIGINT NOT NULL,
  "recorded_at" TEXT NOT NULL,
  "group_id" BIGINT,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "deleted_at" TEXT,
  "status" TEXT NOT NULL DEFAULT '待取样',
  "sampler" TEXT,
  "sampled_at" TEXT,
  "division_id" BIGINT,
  "batch_no" TEXT DEFAULT '',
  "notes" TEXT DEFAULT '',
  "high_item" TEXT,
  "business_no" TEXT NOT NULL DEFAULT '',
  "project_name_snapshot" TEXT NOT NULL DEFAULT '',
  "lab_name_snapshot" TEXT NOT NULL DEFAULT '',
  "method_name_snapshot" TEXT NOT NULL DEFAULT '',
  "high_item_snapshot" TEXT NOT NULL DEFAULT '',
  "coefficient_snapshot" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  "updated_at" TEXT,
  "last_activity_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD"T"HH24:MI:SS'),
  "instrument_code_snapshot" TEXT NOT NULL DEFAULT '',
  "instrument_type_snapshot" TEXT NOT NULL DEFAULT '',
  "created_by_user_id" BIGINT,
  "created_by_username_snapshot" TEXT NOT NULL DEFAULT '',
  "instrument_id_snapshot" BIGINT,
  "subject_user_id" BIGINT,
  "detected_by" TEXT,
  "detected_at" TEXT,
  "extra_fields" TEXT NOT NULL DEFAULT '{}',
  "return_reason" TEXT NOT NULL DEFAULT '',
  "returned_by" TEXT NOT NULL DEFAULT '',
  "returned_at" TEXT,
  "return_confirmed_at" TEXT,
  "return_confirmed_by" TEXT NOT NULL DEFAULT '',
  "voided_at" TEXT,
  "voided_by" TEXT NOT NULL DEFAULT '',
  "void_reason" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS "record_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "module" TEXT NOT NULL,
  "table_name" TEXT NOT NULL,
  "record_id" BIGINT NOT NULL,
  "business_no" TEXT NOT NULL DEFAULT '',
  "event_type" TEXT NOT NULL,
  "from_status" TEXT,
  "to_status" TEXT,
  "operator" TEXT NOT NULL DEFAULT '',
  "operated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "reason" TEXT NOT NULL DEFAULT '',
  "before_json" TEXT,
  "after_json" TEXT
);

CREATE TABLE IF NOT EXISTS "role_permissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" BIGINT NOT NULL,
  "permission_key" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "role_templates" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL DEFAULT '',
  "is_system" BIGINT NOT NULL DEFAULT 1,
  "sort_order" BIGINT NOT NULL DEFAULT 0,
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "role_template_permissions" (
  "template_id" BIGINT NOT NULL,
  "permission_key" TEXT NOT NULL,
  PRIMARY KEY ("template_id", "permission_key")
);

CREATE TABLE IF NOT EXISTS "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT DEFAULT '',
  "is_system" BIGINT NOT NULL DEFAULT 0,
  "sort_order" BIGINT NOT NULL DEFAULT 0,
  "system_key" TEXT NOT NULL DEFAULT '',
  "template_id" BIGINT,
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "sample_info_attachments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "record_id" BIGINT NOT NULL,
  "file_name" TEXT NOT NULL,
  "stored_name" TEXT NOT NULL,
  "file_size" BIGINT NOT NULL,
  "file_type" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "sample_info_column_visibility" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_key" TEXT NOT NULL,
  "column_id" BIGINT NOT NULL,
  "is_visible" BIGINT NOT NULL DEFAULT 1,
  "is_required" BIGINT NOT NULL DEFAULT 0,
  "show_in_form" BIGINT NOT NULL DEFAULT 1,
  "show_in_list" BIGINT NOT NULL DEFAULT 1,
  "show_in_export" BIGINT NOT NULL DEFAULT 1,
  "sort_order" BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "sample_info_columns" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "field_key" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "data_type" TEXT NOT NULL DEFAULT 'text',
  "is_predefined" BIGINT NOT NULL DEFAULT 0,
  "is_required" BIGINT NOT NULL DEFAULT 0,
  "is_active" BIGINT NOT NULL DEFAULT 1,
  "width" BIGINT DEFAULT 100,
  "sort_order" BIGINT DEFAULT 0,
  "options" TEXT,
  "show_in_list" BIGINT NOT NULL DEFAULT 1,
  "show_in_export" BIGINT NOT NULL DEFAULT 1,
  "show_in_form" BIGINT NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" TEXT DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "type_key" TEXT,
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "sample_info_records" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" TEXT NOT NULL DEFAULT '待取样',
  "seq_no" BIGINT NOT NULL,
  "batch_no" TEXT NOT NULL,
  "user_name" TEXT NOT NULL,
  "lab_name" TEXT NOT NULL,
  "project_name" TEXT NOT NULL,
  "submitted_at" TEXT NOT NULL,
  "detection_date" TEXT NOT NULL,
  "main_components" TEXT NOT NULL,
  "detection_type" TEXT NOT NULL,
  "notes" TEXT DEFAULT '',
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" TEXT DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "deleted_at" TEXT,
  "type_key" TEXT DEFAULT '',
  "division_id" BIGINT,
  "quantity" BIGINT NOT NULL DEFAULT 1,
  "extra_fields" TEXT DEFAULT '{}',
  "sampled_by" TEXT NOT NULL DEFAULT '',
  "sampled_at" TEXT,
  "detected_by" TEXT NOT NULL DEFAULT '',
  "business_no" TEXT NOT NULL DEFAULT '',
  "group_id" BIGINT,
  "created_by_user_id" BIGINT,
  "created_by_username_snapshot" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS "sample_info_types" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_key" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT DEFAULT '',
  "color" TEXT DEFAULT '#2e7d32',
  "sort_order" BIGINT DEFAULT 0,
  "is_active" BIGINT NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "sample_records" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" BIGINT NOT NULL,
  "group_id" BIGINT NOT NULL,
  "user_name" TEXT NOT NULL,
  "sample_name" TEXT NOT NULL,
  "sample_count" BIGINT NOT NULL DEFAULT 1,
  "unit" TEXT NOT NULL DEFAULT '个',
  "batch_no" TEXT DEFAULT '',
  "notes" TEXT DEFAULT '',
  "submitted_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "deleted_at" TEXT
);

CREATE TABLE IF NOT EXISTS "system_settings" (
  "key" TEXT,
  "value" TEXT NOT NULL,
  "updated_at" TEXT,
  PRIMARY KEY ("key")
);

CREATE TABLE IF NOT EXISTS "trash_entries" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "entity_type" TEXT NOT NULL,
  "table_name" TEXT NOT NULL,
  "record_id" BIGINT NOT NULL,
  "category" TEXT NOT NULL,
  "module" TEXT NOT NULL DEFAULT 'shared',
  "display_name" TEXT NOT NULL,
  "business_no" TEXT NOT NULL DEFAULT '',
  "snapshot_json" TEXT NOT NULL DEFAULT '{}',
  "delete_reason" TEXT NOT NULL DEFAULT '',
  "deleted_by_user_id" BIGINT,
  "deleted_by_username" TEXT NOT NULL,
  "owner_user_id" BIGINT,
  "owner_group_id" BIGINT,
  "dependency_summary" TEXT NOT NULL DEFAULT '',
  "can_purge" BIGINT NOT NULL DEFAULT 1,
  "deleted_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "restored_at" TEXT,
  "restored_by_user_id" BIGINT,
  "restored_by_username" TEXT,
  "purged_at" TEXT,
  "purged_by_user_id" BIGINT,
  "purged_by_username" TEXT,
  "archive_reference" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS "user_affiliation_group_links" (
  "user_id" BIGINT NOT NULL,
  "affiliation_group_id" BIGINT NOT NULL,
  PRIMARY KEY ("user_id", "affiliation_group_id")
);

CREATE TABLE IF NOT EXISTS "user_affiliation_groups" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "sort_order" BIGINT NOT NULL DEFAULT 0,
  "is_system" BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "user_roles" (
  "user_id" BIGINT NOT NULL,
  "role_id" BIGINT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE IF NOT EXISTS "user_sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "token" TEXT NOT NULL,
  "expires_at" TEXT NOT NULL,
  "keep_signed_in" BIGINT NOT NULL DEFAULT 0,
  "last_seen_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "device_id" TEXT NOT NULL DEFAULT '',
  "device_name" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "division_id" BIGINT,
  "group_id" BIGINT,
  "is_admin" BIGINT NOT NULL DEFAULT 0,
  "is_active" BIGINT NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" TEXT DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "role_id" BIGINT,
  "deleted_at" TEXT,
  "purged_at" TEXT
);

CREATE TABLE IF NOT EXISTS "work_records" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" BIGINT NOT NULL,
  "user_name" TEXT NOT NULL,
  "quantity" BIGINT NOT NULL,
  "recorded_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  "deleted_at" TEXT,
  "batch_no" TEXT DEFAULT '',
  "extra_info" TEXT DEFAULT '',
  "method_id" BIGINT,
  "group_id" BIGINT,
  "multiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  "division_id" BIGINT,
  "high_item" TEXT,
  "business_no" TEXT NOT NULL DEFAULT '',
  "project_name_snapshot" TEXT NOT NULL DEFAULT '',
  "lab_name_snapshot" TEXT NOT NULL DEFAULT '',
  "method_name_snapshot" TEXT NOT NULL DEFAULT '',
  "high_item_snapshot" TEXT NOT NULL DEFAULT '',
  "coefficient_snapshot" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  "updated_at" TEXT,
  "instrument_code_snapshot" TEXT NOT NULL DEFAULT '',
  "instrument_type_snapshot" TEXT NOT NULL DEFAULT '',
  "created_by_user_id" BIGINT,
  "subject_user_id" BIGINT,
  "created_by_username_snapshot" TEXT NOT NULL DEFAULT '',
  "instrument_id_snapshot" BIGINT,
  "detection_division_id" BIGINT,
  "detection_division_name_snapshot" TEXT NOT NULL DEFAULT '',
  "sending_division_id" BIGINT,
  "sending_division_name_snapshot" TEXT NOT NULL DEFAULT '',
  "sending_group_id" BIGINT,
  "sending_group_name_snapshot" TEXT NOT NULL DEFAULT '',
  "source_type" TEXT,
  "source_record_id" BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_work_records_sample_source"
  ON "work_records" ("source_type", "source_record_id")
  WHERE "source_type" IS NOT NULL AND "source_record_id" IS NOT NULL;

ALTER TABLE "audit_log" ADD CONSTRAINT "fk_audit_log_user_id_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "governance_confirmations" ADD CONSTRAINT "fk_governance_confirmations_request_user_id_0" FOREIGN KEY ("request_user_id") REFERENCES "users" ("id");

ALTER TABLE "governance_import_batches" ADD CONSTRAINT "fk_governance_import_batches_operator_user_id_0" FOREIGN KEY ("operator_user_id") REFERENCES "users" ("id");

ALTER TABLE "governance_jobs" ADD CONSTRAINT "fk_governance_jobs_operator_user_id_0" FOREIGN KEY ("operator_user_id") REFERENCES "users" ("id");

ALTER TABLE "method_type_links" ADD CONSTRAINT "fk_method_type_links_method_type_id_0" FOREIGN KEY ("method_type_id") REFERENCES "method_types" ("id") ON DELETE CASCADE;

ALTER TABLE "method_type_links" ADD CONSTRAINT "fk_method_type_links_method_id_1" FOREIGN KEY ("method_id") REFERENCES "methods" ("id") ON DELETE CASCADE;

ALTER TABLE "methods" ADD CONSTRAINT "fk_methods_instrument_id_0" FOREIGN KEY ("instrument_id") REFERENCES "instruments" ("id");

ALTER TABLE "personnel_change_feedback_projects" ADD CONSTRAINT "fk_personnel_change_feedback_projects_project_id_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "personnel_change_feedback_projects" ADD CONSTRAINT "fk_personnel_change_feedback_projects_feedback_id_1" FOREIGN KEY ("feedback_id") REFERENCES "personnel_change_feedbacks" ("id") ON DELETE CASCADE;

ALTER TABLE "personnel_change_feedbacks" ADD CONSTRAINT "fk_personnel_change_feedbacks_created_by_user_id_0" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "personnel_change_feedbacks" ADD CONSTRAINT "fk_personnel_change_feedbacks_responsible_user_id_1" FOREIGN KEY ("responsible_user_id") REFERENCES "users" ("id");

ALTER TABLE "personnel_change_feedbacks" ADD CONSTRAINT "fk_personnel_change_feedbacks_lab_id_2" FOREIGN KEY ("lab_id") REFERENCES "project_groups" ("id");

ALTER TABLE "project_groups" ADD CONSTRAINT "fk_project_groups_division_id_0" FOREIGN KEY ("division_id") REFERENCES "divisions" ("id");

ALTER TABLE "project_lab_links" ADD CONSTRAINT "fk_project_lab_links_group_id_0" FOREIGN KEY ("group_id") REFERENCES "project_groups" ("id") ON DELETE CASCADE;

ALTER TABLE "project_lab_links" ADD CONSTRAINT "fk_project_lab_links_project_id_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;

ALTER TABLE "project_method_links" ADD CONSTRAINT "fk_project_method_links_method_id_0" FOREIGN KEY ("method_id") REFERENCES "methods" ("id") ON DELETE CASCADE;

ALTER TABLE "project_method_links" ADD CONSTRAINT "fk_project_method_links_project_id_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;

ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_high_item_id_0" FOREIGN KEY ("high_item_id") REFERENCES "high_items" ("id") ON DELETE SET NULL;

ALTER TABLE "projects" ADD CONSTRAINT "fk_projects_group_id_1" FOREIGN KEY ("group_id") REFERENCES "project_groups" ("id");

ALTER TABLE "rd_work_records" ADD CONSTRAINT "fk_rd_work_records_subject_user_id_0" FOREIGN KEY ("subject_user_id") REFERENCES "users" ("id");

ALTER TABLE "rd_work_records" ADD CONSTRAINT "fk_rd_work_records_instrument_id_snapshot_1" FOREIGN KEY ("instrument_id_snapshot") REFERENCES "instruments" ("id");

ALTER TABLE "rd_work_records" ADD CONSTRAINT "fk_rd_work_records_created_by_user_id_2" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "rd_work_records" ADD CONSTRAINT "fk_rd_work_records_division_id_3" FOREIGN KEY ("division_id") REFERENCES "divisions" ("id");

ALTER TABLE "rd_work_records" ADD CONSTRAINT "fk_rd_work_records_group_id_4" FOREIGN KEY ("group_id") REFERENCES "project_groups" ("id");

ALTER TABLE "rd_work_records" ADD CONSTRAINT "fk_rd_work_records_project_id_5" FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_role_id_0" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE;

ALTER TABLE "sample_info_attachments" ADD CONSTRAINT "fk_sample_info_attachments_record_id_0" FOREIGN KEY ("record_id") REFERENCES "sample_info_records" ("id") ON DELETE CASCADE;

ALTER TABLE "sample_info_column_visibility" ADD CONSTRAINT "fk_sample_info_column_visibility_column_id_0" FOREIGN KEY ("column_id") REFERENCES "sample_info_columns" ("id") ON DELETE CASCADE;

ALTER TABLE "sample_info_records" ADD CONSTRAINT "fk_sample_info_records_created_by_user_id_0" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "sample_info_records" ADD CONSTRAINT "fk_sample_info_records_group_id_1" FOREIGN KEY ("group_id") REFERENCES "project_groups" ("id");

ALTER TABLE "sample_records" ADD CONSTRAINT "fk_sample_records_group_id_0" FOREIGN KEY ("group_id") REFERENCES "project_groups" ("id");

ALTER TABLE "sample_records" ADD CONSTRAINT "fk_sample_records_project_id_1" FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "trash_entries" ADD CONSTRAINT "fk_trash_entries_deleted_by_user_id_0" FOREIGN KEY ("deleted_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "user_affiliation_group_links" ADD CONSTRAINT "fk_user_affiliation_group_links_affiliation_group_id_0" FOREIGN KEY ("affiliation_group_id") REFERENCES "user_affiliation_groups" ("id") ON DELETE CASCADE;

ALTER TABLE "user_affiliation_group_links" ADD CONSTRAINT "fk_user_affiliation_group_links_user_id_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_role_id_0" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE;

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_user_id_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "user_sessions" ADD CONSTRAINT "fk_user_sessions_user_id_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "users" ADD CONSTRAINT "fk_users_role_id_0" FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "users" ADD CONSTRAINT "fk_users_group_id_1" FOREIGN KEY ("group_id") REFERENCES "project_groups" ("id");

ALTER TABLE "users" ADD CONSTRAINT "fk_users_division_id_2" FOREIGN KEY ("division_id") REFERENCES "divisions" ("id");

ALTER TABLE "work_records" ADD CONSTRAINT "fk_work_records_instrument_id_snapshot_0" FOREIGN KEY ("instrument_id_snapshot") REFERENCES "instruments" ("id");

ALTER TABLE "work_records" ADD CONSTRAINT "fk_work_records_subject_user_id_1" FOREIGN KEY ("subject_user_id") REFERENCES "users" ("id");

ALTER TABLE "work_records" ADD CONSTRAINT "fk_work_records_created_by_user_id_2" FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "work_records" ADD CONSTRAINT "fk_work_records_division_id_3" FOREIGN KEY ("division_id") REFERENCES "divisions" ("id");

ALTER TABLE "work_records" ADD CONSTRAINT "fk_work_records_group_id_4" FOREIGN KEY ("group_id") REFERENCES "project_groups" ("id");

ALTER TABLE "work_records" ADD CONSTRAINT "fk_work_records_project_id_5" FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

CREATE INDEX IF NOT EXISTS "idx_audit_user_time" ON "audit_log" ("user_id", "created_at");

CREATE INDEX IF NOT EXISTS "idx_audit_business_no" ON "audit_log" ("business_no");

CREATE INDEX IF NOT EXISTS "idx_audit_module_time" ON "audit_log" ("module", "created_at");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_backup_file_trash_stored_name" ON "backup_file_trash" ("stored_name");

CREATE INDEX IF NOT EXISTS "idx_divisions_sort" ON "divisions" ("sort_order");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_divisions_name" ON "divisions" ("name");

CREATE INDEX IF NOT EXISTS "idx_governance_confirmation_expiry" ON "governance_confirmations" ("expires_at", "used_at");

CREATE INDEX IF NOT EXISTS "idx_governance_import_module_time" ON "governance_import_batches" ("module", "created_at");

CREATE INDEX IF NOT EXISTS "idx_governance_jobs_module_time" ON "governance_jobs" ("module", "created_at");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_high_items_name" ON "high_items" ("name");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_instruments_name_unique" ON "instruments" ("name");

CREATE INDEX IF NOT EXISTS "idx_instruments_active" ON "instruments" ("is_active");

CREATE INDEX IF NOT EXISTS "idx_instruments_type" ON "instruments" ("instrument_type");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_instruments_code" ON "instruments" ("code");

CREATE INDEX IF NOT EXISTS "idx_log_archive_batches_type_time" ON "log_archive_batches" ("archive_type", "created_at");

CREATE INDEX IF NOT EXISTS "idx_maintenance_jobs_type_time" ON "maintenance_jobs" ("job_type", "started_at");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_method_types_name" ON "method_types" ("name");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_methods_name_instrument_unique" ON "methods" ("name", "instrument_id");

CREATE INDEX IF NOT EXISTS "idx_methods_instrument" ON "methods" ("instrument_id");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_methods_code_present" ON "methods" ("method_code") WHERE "method_code" <> '';

CREATE INDEX IF NOT EXISTS "idx_personnel_feedback_deleted" ON "personnel_change_feedbacks" ("deleted_at", "status");

CREATE INDEX IF NOT EXISTS "idx_personnel_feedback_lab_time" ON "personnel_change_feedbacks" ("lab_id", "created_at");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_personnel_feedback_notice_no" ON "personnel_change_feedbacks" ("notice_no");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_project_groups_name_unique" ON "project_groups" ("name");

CREATE INDEX IF NOT EXISTS "idx_groups_division" ON "project_groups" ("division_id");


CREATE UNIQUE INDEX IF NOT EXISTS "idx_projects_name_unique" ON "projects" ("name");

CREATE INDEX IF NOT EXISTS "idx_projects_status_active" ON "projects" ("project_status", "is_active");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_projects_name_group" ON "projects" ("name", "group_id");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_rd_record_columns_name" ON "rd_record_columns" ("name");

CREATE INDEX IF NOT EXISTS "idx_rd_instrument_time" ON "rd_work_records" ("instrument_id_snapshot", "recorded_at");

CREATE INDEX IF NOT EXISTS "idx_rd_subject_time" ON "rd_work_records" ("subject_user_id", "recorded_at");

CREATE INDEX IF NOT EXISTS "idx_rd_creator_time" ON "rd_work_records" ("created_by_user_id", "recorded_at");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_rd_business_no" ON "rd_work_records" ("business_no");

CREATE INDEX IF NOT EXISTS "idx_rd_records_group_date" ON "rd_work_records" ("group_id", "recorded_at");

CREATE INDEX IF NOT EXISTS "idx_rd_records_user_date" ON "rd_work_records" ("user_name", "recorded_at");

CREATE INDEX IF NOT EXISTS "idx_rd_records_deleted_date" ON "rd_work_records" ("deleted_at", "recorded_at");

CREATE INDEX IF NOT EXISTS "idx_rd_records_division" ON "rd_work_records" ("division_id");

CREATE INDEX IF NOT EXISTS "idx_rd_records_deleted" ON "rd_work_records" ("deleted_at");

CREATE INDEX IF NOT EXISTS "idx_rd_records_user" ON "rd_work_records" ("user_name");

CREATE INDEX IF NOT EXISTS "idx_rd_records_date" ON "rd_work_records" ("recorded_at");

CREATE INDEX IF NOT EXISTS "idx_rd_records_activity" ON "rd_work_records" ("last_activity_at" DESC, "id" DESC);

CREATE INDEX IF NOT EXISTS "idx_rd_records_method" ON "rd_work_records" ("method_id");

CREATE INDEX IF NOT EXISTS "idx_rd_records_project" ON "rd_work_records" ("project_id");

CREATE INDEX IF NOT EXISTS "idx_record_events_operator_time" ON "record_events" ("operator", "operated_at");

CREATE INDEX IF NOT EXISTS "idx_record_events_record" ON "record_events" ("table_name", "record_id", "operated_at");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_role_permissions_unique" ON "role_permissions" ("role_id", "permission_key");

CREATE INDEX IF NOT EXISTS "idx_role_perms_role" ON "role_permissions" ("role_id");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_roles_name" ON "roles" ("name");

CREATE INDEX IF NOT EXISTS "idx_sia_record" ON "sample_info_attachments" ("record_id");

CREATE INDEX IF NOT EXISTS "idx_scv_type" ON "sample_info_column_visibility" ("type_key");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_sample_info_column_visibility_type_column" ON "sample_info_column_visibility" ("type_key", "column_id");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_sample_info_columns_field_key" ON "sample_info_columns" ("field_key");

CREATE INDEX IF NOT EXISTS "idx_sample_info_group_time" ON "sample_info_records" ("group_id", "submitted_at");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_si_business_no" ON "sample_info_records" ("business_no");

CREATE INDEX IF NOT EXISTS "idx_sir_type_submitted" ON "sample_info_records" ("type_key", "submitted_at");

CREATE INDEX IF NOT EXISTS "idx_sir_status_submitted" ON "sample_info_records" ("status", "submitted_at");

CREATE INDEX IF NOT EXISTS "idx_sir_deleted_submitted" ON "sample_info_records" ("deleted_at", "submitted_at");

CREATE INDEX IF NOT EXISTS "idx_sir_type_key" ON "sample_info_records" ("type_key");

CREATE INDEX IF NOT EXISTS "idx_sir_submitted" ON "sample_info_records" ("submitted_at");

CREATE INDEX IF NOT EXISTS "idx_sir_status" ON "sample_info_records" ("status");

CREATE INDEX IF NOT EXISTS "idx_sir_detection_type" ON "sample_info_records" ("detection_type");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_sample_info_types_type_key" ON "sample_info_types" ("type_key");

CREATE INDEX IF NOT EXISTS "idx_sample_deleted" ON "sample_records" ("deleted_at");

CREATE INDEX IF NOT EXISTS "idx_sample_date" ON "sample_records" ("submitted_at");

CREATE INDEX IF NOT EXISTS "idx_sample_user" ON "sample_records" ("user_name");

CREATE INDEX IF NOT EXISTS "idx_sample_group" ON "sample_records" ("group_id");

CREATE INDEX IF NOT EXISTS "idx_sample_project" ON "sample_records" ("project_id");

CREATE INDEX IF NOT EXISTS "idx_trash_scope" ON "trash_entries" ("module", "owner_user_id", "owner_group_id");

CREATE INDEX IF NOT EXISTS "idx_trash_active_time" ON "trash_entries" ("deleted_at");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_trash_active_entity" ON "trash_entries" ("table_name", "record_id") WHERE "restored_at" IS NULL AND "purged_at" IS NULL;

CREATE INDEX IF NOT EXISTS "idx_user_affiliation_group_links_group" ON "user_affiliation_group_links" ("affiliation_group_id", "user_id");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_affiliation_groups_name" ON "user_affiliation_groups" ("name");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_affiliation_groups_code" ON "user_affiliation_groups" ("code");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_sessions_user_device" ON "user_sessions" ("user_id", "device_id");

CREATE INDEX IF NOT EXISTS "idx_sessions_token" ON "user_sessions" ("token");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_sessions_token" ON "user_sessions" ("token");

CREATE INDEX IF NOT EXISTS "idx_users_username" ON "users" ("username");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_username" ON "users" ("username");

CREATE INDEX IF NOT EXISTS "idx_work_instrument_time" ON "work_records" ("instrument_id_snapshot", "recorded_at");

CREATE INDEX IF NOT EXISTS "idx_work_subject_time" ON "work_records" ("subject_user_id", "recorded_at");

CREATE INDEX IF NOT EXISTS "idx_work_creator_time" ON "work_records" ("created_by_user_id", "recorded_at");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_work_business_no" ON "work_records" ("business_no");

CREATE INDEX IF NOT EXISTS "idx_records_group_date" ON "work_records" ("group_id", "recorded_at");

CREATE INDEX IF NOT EXISTS "idx_records_user_date" ON "work_records" ("user_name", "recorded_at");

CREATE INDEX IF NOT EXISTS "idx_records_deleted_date" ON "work_records" ("deleted_at", "recorded_at");

CREATE INDEX IF NOT EXISTS "idx_records_division" ON "work_records" ("division_id");

CREATE INDEX IF NOT EXISTS "idx_records_method" ON "work_records" ("method_id");

CREATE INDEX IF NOT EXISTS "idx_records_deleted" ON "work_records" ("deleted_at");

CREATE INDEX IF NOT EXISTS "idx_records_user" ON "work_records" ("user_name");

CREATE INDEX IF NOT EXISTS "idx_records_date" ON "work_records" ("recorded_at");

CREATE INDEX IF NOT EXISTS "idx_records_project" ON "work_records" ("project_id");

-- v2.2.8 性能优化索引
CREATE INDEX IF NOT EXISTS "idx_project_lab_links_group" ON "project_lab_links" ("group_id", "project_id");

CREATE INDEX IF NOT EXISTS "idx_project_method_links_project" ON "project_method_links" ("project_id", "method_id");

CREATE INDEX IF NOT EXISTS "idx_methods_active_instrument" ON "methods" ("is_active", "instrument_id") WHERE "is_active" = 1;

INSERT INTO schema_migrations(version) VALUES ('1.1.0-beta.1') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS notification_channels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  channel_type TEXT NOT NULL DEFAULT 'dingtalk_robot',
  webhook_url TEXT NOT NULL,
  secret TEXT NOT NULL DEFAULT '',
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS notification_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, event_type TEXT NOT NULL DEFAULT 'sample_submitted', group_id BIGINT,
  project_name TEXT NOT NULL DEFAULT '', detection_type TEXT NOT NULL DEFAULT '', channel_id BIGINT,
  recipient_user_ids TEXT NOT NULL DEFAULT '[]', is_default BIGINT NOT NULL DEFAULT 0, is_active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id BIGINT NOT NULL, dedupe_key TEXT NOT NULL UNIQUE,
  payload_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', next_attempt_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'), updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);
CREATE TABLE IF NOT EXISTS notification_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id BIGINT NOT NULL, channel_id BIGINT NOT NULL,
  status TEXT NOT NULL, attempts BIGINT NOT NULL DEFAULT 0, response_summary TEXT NOT NULL DEFAULT '', last_error TEXT NOT NULL DEFAULT '',
  next_attempt_at TEXT, sent_at TEXT, created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'), UNIQUE(event_id, channel_id)
);
CREATE TABLE IF NOT EXISTS in_app_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
  title TEXT NOT NULL, body TEXT NOT NULL, target_url TEXT NOT NULL DEFAULT '', is_read BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'), UNIQUE(event_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_notification_events_pending ON notification_events(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_notification_rules_match ON notification_rules(event_type, is_active, group_id);
CREATE INDEX IF NOT EXISTS idx_in_app_notifications_user ON in_app_notifications(user_id, is_read, created_at);
INSERT INTO schema_migrations(version) VALUES ('1.1.0-beta.10-notifications') ON CONFLICT DO NOTHING;

COMMIT;
